name = "image"
account_id = "2ca8f087834868e70427f43cb09afcce"
main = "src/index.ts"
compatibility_date = "2023-01-03"
usage_model = "bundled"

[vars]
DEDICATED_GATEWAY = 'https://real.myfilebase.com'
DEDICATED_BACKUP_GATEWAY = 'https://bronze-sophisticated-mongoose-117.mypinata.cloud'
CLOUDFLARE_GATEWAY = 'https://cloudflare-ipfs.com'
CF_IMAGE_ACCOUNT = '2ca8f087834868e70427f43cb09afcce'
CF_IMAGE_ID = 'TbEOGfUBcfmfflqdtuuZVA'

[[r2_buckets]]
binding = 'MY_BUCKET'
bucket_name = 'ipfs-cache'
preview_bucket_name = 'ipfs-cache'
